openapi: 3.0.0
info:
  title: Jobs API
  contact: {}
  version: "1.0"
servers:
  - url: https://jobs-api-nine.vercel.app/api/v1
    variables: {}
paths:
  /jobs:
    get:
      tags:
        - Jobs
      summary: Get Jobs
      description: Get all of a user's saved jobs
      operationId: GetJobs
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    post:
      tags:
        - Jobs
      summary: Create Job
      description: Save a job to a user's account
      operationId: CreateJob
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              example:
                company: Google
                position: Software Engineer
            example:
              company: Google
              position: Software Engineer
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /jobs/{id}:
    get:
      tags:
        - Jobs
      summary: Get Single Job
      description: Get details for a single job
      operationId: GetSingleJob
      parameters:
        - name: id
          in: path
          description: The Job ID
          required: true
          style: simple
          schema:
            type: string
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    patch:
      tags:
        - Jobs
      summary: Update Job
      description: Update a user's job
      operationId: UpdateJob
      parameters:
        - name: id
          in: path
          description: The Job ID
          required: true
          style: simple
          schema:
            type: string
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              example:
                company: Google
                position: Software Engineer
            example:
              company: Google
              position: Software Engineer
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    delete:
      tags:
        - Jobs
      summary: Delete Job
      description: Delete a job
      operationId: DeleteJob
      parameters:
        - name: id
          in: path
          description: The Job ID
          required: true
          style: simple
          schema:
            type: string
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      description: Login an existing user
      operationId: LoginUser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              example:
                email: bob@mail.com
                password: secret_password
            example:
              email: bob@mail.com
              password: secret_password
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      description: Register a new user
      operationId: RegisterUser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              example:
                name: Bobby Brown
                email: bob@mail.com
                password: secret_password
            example:
              name: Bobby Brown
              email: bob@mail.com
              password: secret_password
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Auth
    description: ""
  - name: Jobs
    description: ""
